### ISSUE TITLE
Return better config_diff for scheduled execution

### ISSUE THREAD

**Issue by muga** [treasure-data/embulk-input-sfdc#28]
Could you consider better config_diff? Or the plugin doesn't need to be executed periodically?
In the current implementation, an empty config_diff is returned (https://github.com/treasure-data/embulk-input-sfdc/blob/master/lib/embulk/input/sfdc.rb#L38). 
reference: https://github.com/treasure-data/embulk-input-marketo/issues/18

**Comment by yoshihara** [comment]
Sorry too late, this issue is resolved by embulk-input-sfdc 0.0.4 and it is released already :bow:

**Comment by yoshihara** [comment]
Oops!!! I made a miss...I misunderstood other issue...

**Comment by uu59** [comment]
We need time column for scheduled execution.

Salesforce has [tons of standard objects](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_list.htm) and each object has different time column.
e.g. Account has `PersonLastCUUpdateDate`, Contact has `LastCUUpdateDate`, etc.
Unfortunately the plugin can't detect what is `target` time column automatically :cry: 

Any idea of how to implete this feature request?

**Comment by nahi** [comment]
Generally, "LastModifiedDate" is the one: https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/system_fields.htm

But as the page says "found on most objects" there're a few objects that do not have the field. So "If it has  LastModifiedDate use it, otherwise ignore" should be a good start.

**Comment by uu59** [comment]
Looks good!
We'll try it

**Comment by uu59** [comment]
https://github.com/treasure-data/embulk-input-sfdc/pull/39
I've implemented it and released as v0.1.1 using `LastModifiedDate` column.

**Comment by uu59** [comment]
If you have any problems, please reopen this.
